server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: catalog
        port: 27018

  rabbitmq:
    username: guest
    password: guest
    localhost: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue
   
message: Serie & Movie UP

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      subscription:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      subscription:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError


